### ISSUE TITLE
ADSimDetector master branch compile branch fails with ADCore/master. The Tag R2-8 compiles fine..

### ISSUE THREAD

**Issue by kgofron** [areaDetector/ADSimDetector#14]
../simDetectorNoIOC.cpp:29:45: error: ‘asynParamClient’ has not been declared
   callbackStruct(const char *paramStringIn, asynParamClient *pClientIn, class simDetectorDemo *pSimDetectorDemoIn)
                                             ^
../simDetectorNoIOC.cpp:32:3: error: ‘asynParamClient’ does not name a type
   asynParamClient *pClient;
   ^
../simDetectorNoIOC.cpp: In constructor ‘callbackStruct::callbackStruct(const char*, int*, simDetectorDemo*)’:
../simDetectorNoIOC.cpp:30:33: error: class ‘callbackStruct’ does not have any field named ‘pClient’
   : paramString(paramStringIn), pClient(pClientIn), pSimDetectorDemo(pSimDetectorDemoIn), pasynUser(0) {};
                                 ^
../simDetectorNoIOC.cpp: In constructor ‘simDetectorDemo::simDetectorDemo()’:
../simDetectorNoIOC.cpp:108:45: error: no matching function for call to ‘asynPortClient::asynPortClient(const char [5])’
   pSimClient_   =  new asynPortClient("SIM1");
                                             ^
../simDetectorNoIOC.cpp:108:45: note: candidates are:
In file included from ../simDetectorNoIOC.cpp:13:0:
/eApps/epics/support/asyn/include/asynPortClient.h:44:5: note: asynPortClient::asynPortClient(const char*, int, const char*, const char*, double)
     asynPortClient(const char *portName, int addr, const char* asynInterfaceType, const char *drvInfo, double timeout);
     ^
/eApps/epics/support/asyn/include/asynPortClient.h:44:5: note:   candidate expects 5 arguments, 1 provided
/eApps/epics/support/asyn/include/asynPortClient.h:42:23: note: asynPortClient::asynPortClient(const asynPortClient&)
 class epicsShareClass asynPortClient {
                       ^
/eApps/epics/support/asyn/include/asynPortClient.h:42:23: note:   no known conversion for argument 1 from ‘const char [5]’ to ‘const asynPortClient&’
../simDetectorNoIOC.cpp:109:16: error: ‘class asynPortClient’ has no member named ‘write’
   pSimClient_->write(NDArrayCallbacksString, 1);           // Enable NDArray callbacks
                ^
../simDetectorNoIOC.cpp:110:16: error: ‘class asynPortClient’ has no member named ‘write’
   pSimClient_->write(ADGainString, 1.0);                   // Set the Gain to 1.0

................................
/eApps/epics/base/configure/RULES_BUILD:242: recipe for target 'simDetectorNoIOC.o' failed
make[5]: *** [simDetectorNoIOC.o] Error 1
/eApps/epics/base/configure/RULES_ARCHS:58: recipe for target 'install.linux-x86_64' failed
make[4]: *** [install.linux-x86_64] Error 2
/eApps/epics/base/configure/RULES_DIRS:84: recipe for target 'src.install' failed
make[3]: *** [src.install] Error 2
/eApps/epics/base/configure/RULES_DIRS:84: recipe for target 'simDetectorNoIOCApp.install' failed
make[2]: *** [simDetectorNoIOCApp.install] Error 2
/eApps/epics/base/configure/RULES_DIRS:84: recipe for target 'simDetectorNoIOC.install' failed
make[1]: *** [simDetectorNoIOC.install] Error 2
make[1]: *** Waiting for unfinished jobs....
/eApps/epics/support/areaDetector/ADSupport/lib/linux-x86_64/libjp2.a(jas_stream.o): In function `jas_stream_tmpfile':
/eApps/epics/support/areaDetector/ADSupport/supportApp/GraphicsMagickSrc/jp2/src/libjasper/O.linux-x86_64/../../../../../../supportApp/GraphicsMagickSrc/jp2/src/libjasper/base/jas_stream.c:368: warning: the use of `tmpnam' is dangerous, better use `mkstemp'
/eApps/epics/base/configure/RULES_DIRS:84: recipe for target 'iocs.install' failed
make: *** [iocs.install] Error 2

**Comment by MarkRivers** [comment]
You are building the master branch of ADSimDetector.  That currently requires the master branch of asyn, where asynPortClient has had some enhancements.
