### ISSUE TITLE
64bit integers not supported yet

### ISSUE THREAD

**Issue by ralphlange** [areaDetector/ADSimDetector#16]
Compiling against Base 7.0.3.1 and ADCore 3.8 yields:

```
/usr/bin/g++  -D_GNU_SOURCE -D_DEFAULT_SOURCE           -D_X86_64_  -DUNIX  -Dlinux     -O3   -Wall      -mtune=generic      -m64 -std=c++11 -fPIC -I. -I../O.Common -I. -I. -I.. -I../../../include/compiler/gcc -I../../../include/os/Linux -I../../../include -I/opt/codac-6.2/epics/include/compiler/gcc -I/opt/codac-6.2/epics/include/os/Linux -I/opt/codac-6.2/epics/include       -I/opt/codac-6.2/include  -c ../simDetector.cpp
[WARN] ../simDetector.cpp: In member function 'int simDetector::computeImage()':
[WARN] ../simDetector.cpp:624:12: warning: enumeration value 'NDInt64' not handled in switch [-Wswitch]
[WARN] switch (dataType) {
[WARN] ^
[WARN] ../simDetector.cpp:624:12: warning: enumeration value 'NDUInt64' not handled in switch [-Wswitch]
```

**Comment by MarkRivers** [comment]
ADsimDetector is released independently of ADCore. Did you use the latest release of ADSimdetector?

**Comment by MarkRivers** [comment]
When you checkout areaDetector R3-8 you get ADCore R3-8 and the latest tag of ADSupport.  However, you get the master branch of ADSimDetector and all other detectors at the time that areaDetector tag was applied.  ADSimDetector and all other detectors are tagged and released independently of ADCore and areaDetector.

This is the from the ADSimDetector R2-10 RELEASE.md
**************************
R2-10 (October 22, 2019)
=========================
* Added support for NDArray datatypes NDInt64 and NDUInt64
  * This requires asyn R4-37 and ADCore R3-8
* Added iocSimDetector/testHDF5Compression.py to test HDF5 compression.
* Added Time64 attribute to iocSimDetector/simDetectorAttributes.xml.  This tests attributes of type NDAttrUInt64.
**************************

So you need to checkout R2-10 of ADSimDetector.

**Comment by ralphlange** [comment]
Oops, my bad.

For CODAC, I am only using released versions, never snapshots.
I was compiling my "old" CODAC version (2.8) for comparison, then my "new" CODAC version (2.10) and confused the two make outputs.

Sorry for the false alarm; I am closing the ticket.
